# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build flutter app

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.0"
          channel: "stable"
      - run: flutter pub get
      - run: flutter build apk

      - name: Upload android apk file
        uses: actions/upload-artifact@v3
        with:
          name: app.apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 5
